### ISSUE TITLE
Does not link, when build on ubuntu 20.04

### ISSUE THREAD

**Issue by Amadrath** [ChimeraTK/ControlSystemAdapter-EPICS-IOC-Adapter#4]
When building a server against EPICS on an Ubuntu 20.04, linking fails with the following errors:

> /usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_attach_context'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::beaconPeriod(epicsGuard<epicsMutex>&) const'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbr_text'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asDumpHash'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asDumpHagFP'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_read_access'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'testDiag'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'typeinfo for cacChannel'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSignalInstallSigAlarmIgnore'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbf_text'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_set_default_alloc_funcs'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asChangeGroup'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asComputeAllAsg'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::getHostName(epicsGuard<epicsMutex>&, char*, unsigned int) const'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacContext::~cacContext()'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_replace_access_rights_event'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerGetHighWaterMark'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asRegisterClientCallback'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'osiSockDiscoverBroadcastAddresses'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'addAddrToChannelAccessAddressList'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'testAbort'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asPutClientPvt'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacService::~cacService()'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_message'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerGetUsed'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asInitFile'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'testFail'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ipAddrToDottedIP'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_free'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'bucketShow'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'bucketCreate'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asDumpFP'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_preemtive_callback_is_enabled'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asGetMemberPvt'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asAddMember'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'taskwdInsert'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsMessageQueueReceiveWithTimeout'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_array_put'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_state'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asRemoveClient'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'osiSufficentSpaceInPool'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSignalInstallSigPipeIgnore'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_complete_parse'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'freeListInitPvt'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_element_count'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asComputeAsg'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asActive'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'calcErrorStr'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSignalInstallSigHupIgnore'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'freeListCalloc'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::ca_v42_ok(epicsGuard<epicsMutex>&) const'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'typeinfo for cacContext'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesLockedCreate'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesDelete'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesUsedBytes'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerIsEmpty'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_field_type'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'taskwdInit'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbExtractArrayFromRec'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_free_error'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesResetHighWaterMark'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_get_error'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerResetHighWaterMark'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesPut'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_dump_dbr'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'chfPluginEnumString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_array_get'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtRawToEngBpt'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'calcPerform'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'freeListFree'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asTrapWriteAfterWrite'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsAlarmConditionStrings'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_create_channel'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSpinDestroy'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asGetClientPvt'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbr_value_size'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ellSortStable'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSpinCreate'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtEngToRawBpt'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::searchAttempts(epicsGuard<epicsMutex>&) const'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'testOk'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsTimerQueueRelease'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtInt64ToString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asDumpRulesFP'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerLockedCreate'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesHighWaterMark'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_search_and_connect'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_host_name'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtInt32ToString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_array_put_callback'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtInt64ToHexString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'caInstallDefaultService(cacService&)'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerPush'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_array_get_callback'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtUInt64ToHexString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsTimerStartDelay'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsTimerQueueAllocate'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesGet'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asFreeAll'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSocketEnableAddressUseForDatagramFanout'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingBytesSize'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_clear_channel'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsAlarmSeverityStrings'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtDoubleToString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSpinUnlock'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbr_text_invalid'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'bucketAddItemUnsignedId'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerPop'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'pasbase'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_context_destroy'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSocketSystemCallInterruptMechanismQuery'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asTrapWriteBeforeWithData'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_parse'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsINF'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_write_access'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbr_size'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'freeListCleanup'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsRingPointerDelete'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSignalRaiseSigAlarm'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'removeDuplicateAddresses'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::~cacChannel()'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_alloc'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::pHostName(epicsGuard<epicsMutex>&) const'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_pend_event'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'caNetConvert'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'taskwdRemove'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'bucketRemoveItemUnsignedId'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbr_value_offset'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_add_exception_event'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'yajl_get_bytes_consumed'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtUInt32ToString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsConvertDoubleToFloat'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'freeListItemsAvail'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'libComRegister'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_puser'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_current_context'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_context_create'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbExtractArrayFromBuf'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asPutMemberPvt'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtUInt64ToString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'bucketLookupItemUnsignedId'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'postfix'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_pend_io'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asAddClient'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_context_status'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsMessageQueueCreate'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asDumpMemFP'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsTimerQueueCreateTimer'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsTimerCancel'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbr_text_dim'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_flush_io'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_clear_event'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_signal_with_file_and_lineno'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsNAN'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbf_text_invalid'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_add_masked_array_event'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'chfPluginRegister'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSocketEnableAddressReuseDuringTimeWaitState'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'dbf_text_dim'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsMessageQueueSend'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::accessRights(epicsGuard<epicsMutex>&) const'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'epicsSpinLock'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'ca_name'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cvtFloatToString'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::receiveWatchdogDelay(epicsGuard<epicsMutex>&) const'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asDumpUagFP'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'asCalloc'
/usr/bin/ld: /home/countzero/ChimeraTK/install/lib/libChimeraTK-ControlSystemAdapter-EPICS-IOC-Adapter.so: undefined reference to 'cacChannel::connected(epicsGuard<epicsMutex>&) const'

These errors do not occur, when build on 16.04 or against the DOOCS adapter in 20.04. Tested with Watchdog and Mockup Server.

**Comment by ckampm** [comment]
This is (partly?) a link order issue. As far as I have already checked, `libdbCore.a` requires symbols that are defined in `libCom.a`, swapping these in the `target_link_libraries` calls in CMakeLists.txt reduces the number of unresolved symbols.

I don't know why this was tolerated by `ld` in Ubuntu 16.04. If somebody knows EPICS documentation on linking the libraries, this would be helpful, but we can also work it out otherwise.

**Comment by ckampm** [comment]
I reordered the other static EPICS libraries and could link a server on 16.04 and 20.04. Fix is in c6fc50891f6e04e84fb551fd2efbde321862e354.
